### ISSUE TITLE
Can not get rolling update to work

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-scholars/openshift-starter-guides#1]
This step https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/nationalparks-java-pipeline-codechanges-github.html#rollback is not working for me, could it be because it always uses the latest image ? 

I also do not get the warning that is shown in the instructions "Warning: the following images triggers were disabled: nationalparks:latest" 

@blues-man

**Comment by blues-man** [comment]
I need to test it again, that's not expected.

**Comment by blues-man** [comment]
Right, using latest avoids rolling back, I missed this step, I need to fix this thanks for reporting.

**Comment by blues-man** [comment]
It looks that using the YAML editing now it keeps the trigger on, that's why I was adding that part on the Tekton task about using latest (like for a Deployment)

I'm gonna push a fix replacing the YAML editing with this command to disable triggers:
```oc set triggers dc nationalparks --manual ```

Then leaving only `rollout` in `redeploy` Task
