### ISSUE TITLE
Separate clearly the alternative ways to interact with OpenShift (CLI or OpenShift Console)

### ISSUE THREAD

**Issue by mcouliba** [redhat-scholars/openshift-starter-guides#11]
To interact with OpenShift, there are 2 main ways used in the workshop: CLI or OpenShift Console.
In the instruction, like in 'Routes' section for example, it is a bit confused and it look like we we have to run all the commands, both CLI and from the OpenShift Console which is not the case.

This example could be applied to the whole workshop.
Probably something like you have in the 'Explore OpenShift/The Web Console' is the solution (CLI vs OpenShift Console)

<img width="1391" alt="Capture d’écran 2020-10-29 à 11 58 57" src="https://user-images.githubusercontent.com/20398651/97559855-42422f80-19de-11eb-9b75-8a75f39a1ce2.png">

**Comment by cedricclyburn** [comment]
Sorry for the late response, we've added this sort of alternation throughout the lab in the latest 4.11 update!
