### ISSUE TITLE
Missing '--' separator in 'oc exec' command

### ISSUE THREAD

**Issue by eschabell** [redhat-scholars/openshift-starter-guides#16]
In chapter "Connecting to a Container" in section "Exercise: Execute a command in a Container" I have to add the missing "--" in oc exec command or whoami will generate an error:

$ oc exec parksmap-2-db7r8 whoami

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
1000580000

Attached screenshot shows command without separator, should be:

$ oc exec parksmap-2-db7r8 -- whoami

1000580000

![Screenshot 2020-11-02 at 11 31 33](https://user-images.githubusercontent.com/437001/97858151-04efe180-1cff-11eb-8200-8af160c50597.png)

**Comment by blues-man** [comment]
Thanks @eschabell !
