### ISSUE TITLE
Node.js labels should be Java labels

### ISSUE THREAD

**Issue by eschabell** [redhat-scholars/openshift-starter-guides#17]
In chapter "Connecting to database" in section "Exercise: Working with Labels" below the command 'oc describe route nationalparks' the output image shows nodejs instead of Java for below listed BOLD lines from actual output:

$ oc describe route nationalparks
Name:			nationalparks
Namespace:		appdev-in-cloud
Created:		13 minutes ago
Labels:			app=appdev-in-cloud
			app.kubernetes.io/component=nationalparks
			app.kubernetes.io/instance=nationalparks
			**app.kubernetes.io/name=java**
			app.kubernetes.io/part-of=appdev-in-cloud
			**app.openshift.io/runtime=java**
			app.openshift.io/runtime-version=11
			component=nationalparks
			role=backend
Annotations:		openshift.io/host.generated=true
Requested Host:		nationalparks-appdev-in-cloud.apps-crc.testing
			  exposed on router default (host apps-crc.testing) 13 minutes ago
Path:			<none>
TLS Termination:	<none>
Insecure Policy:	<none>
Endpoint Port:		8080-tcp

Service:	nationalparks
Weight:		100 (100%)
Endpoints:	10.116.0.73:8778, 10.116.0.73:8443, 10.116.0.73:8080

**Comment by blues-man** [comment]
It was a wrong paste from the NodeJS one :) Thanks!
