### ISSUE TITLE
How to add multiple labels to the deployment

### ISSUE THREAD

**Issue by kameshsampath** [redhat-scholars/openshift-starter-guides#19]
In this section https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/parksmap-container-image.html, when the user in instructed to add labels, there is no clue on how to add e.g. command seperated, semicolon seperated  or tab seperated. It will be nice to give that clue to the user

**Comment by cedricclyburn** [comment]
Instructions have been added, sorry for the late response!
