### ISSUE TITLE
%PROJECT_NAME% shown instead of the actual project name in several places

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-scholars/openshift-starter-guides#2]
Probably in variable not set in antora ?

**Comment by blues-man** [comment]
The workshop work with Antora variables + Query params, at the moment the project name is a query param, do you can have it this way:

https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/common-explore.html?CLUSTER_SUBDOMAIN=apps-crc.testing&PROJECT_NAMESPACE=workshop&USERNAME=foo&PASSWORD=foo

**Comment by blues-man** [comment]
@sebastienblanc I think it makes more sense to have it as a static Antora variable, so for this `roks` branch it's gonna be always `workshop`
