### ISSUE TITLE
On some places the link to the parksmap app does not work 

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-scholars/openshift-starter-guides#3]
Like here, the link does not work : 
<img width="826" alt="Screenshot 2020-10-19 at 21 28 27" src="https://user-images.githubusercontent.com/335133/96502526-358d4100-1252-11eb-9c3d-604dcd0fb351.png">

**Comment by blues-man** [comment]
That link is built with Query Params, so it need the `CLUSTER_SUBDOMAIN` variable from the URL like:

https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/common-explore.html?CLUSTER_SUBDOMAIN=apps-crc.testing&PROJECT_NAMESPACE=workshop&USERNAME=foo&PASSWORD=foo

**Comment by blues-man** [comment]
Fixed in #12
