### ISSUE TITLE
Guide mentions namespace "User1" instead of "workshop"

### ISSUE THREAD

**Issue by kkoenen** [redhat-scholars/openshift-starter-guides#30]
Several occurances, also in some instructions. Mentioning these, but there are more:

[here it's assuming the parksmap application runs in a namespace called "User1"](https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/parksmap-permissions.html?CLUSTER_SUBDOMAIN=rhd-fra02-mar17-2297201-4c50a18a6ae19b704aa10d04d75751f8-0000.eu-de.containers.appdomain.cloud&USERNAME=rh-dev-1232&PASSWORD=m3jjizit&LOGIN=https%3A%2F%2Fiam.cloud.ibm.com%2Fidentity%2Fdevcluster%2Fauthorize%3Fclient_id%3DHOP55v1CCT%26response_type%3Dcode%26state%3Dhttps%253A%252F%252Fcloud.ibm.com%252Fkubernetes%252Fclusters%252Fc18uam6f04opcq7bjct0%252Foverview%26redirect_uri%3Dhttps%253A%252F%252Fcloud.ibm.com%252Flogin%252Fcallback#grant_serviceaccount_view_permissions).

On [this page](https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/parksmap-container-image.html?CLUSTER_SUBDOMAIN=rhd-fra02-mar17-2297201-4c50a18a6ae19b704aa10d04d75751f8-0000.eu-de.containers.appdomain.cloud&USERNAME=rh-dev-1232&PASSWORD=m3jjizit&LOGIN=https%3A%2F%2Fiam.cloud.ibm.com%2Fidentity%2Fdevcluster%2Fauthorize%3Fclient_id%3DHOP55v1CCT%26response_type%3Dcode%26state%3Dhttps%253A%252F%252Fcloud.ibm.com%252Fkubernetes%252Fclusters%252Fc18uam6f04opcq7bjct0%252Foverview%26redirect_uri%3Dhttps%253A%252F%252Fcloud.ibm.com%252Flogin%252Fcallback) too.

And in [this screenshot](https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/_images/parksmap-permissions-membership-serviceaccount-edit.png).

Another example: https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/_images/nationalparks-databases-catalog-databases-mongodb-config.png

**Comment by cedricclyburn** [comment]
Looks like this has been fixed, sorry for the late response!
