### ISSUE TITLE
Broken Link in OpenShift S2I documentation

### ISSUE THREAD

**Issue by gonzalezcaf** [redhat-scholars/openshift-starter-guides#35]
Hi guys, in the OCP Starter Guides (https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/nationalparks-java.html), there is a broken link regarding to  OpenShift S2I documentation (https://docs.openshift.com/container-platform/4.6/creating_images/s2i.html)

**Comment by gonzalezcaf** [comment]
Hi, there's other broken link in the OCP Starter Guides (https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.6/mlbparks-debugging.html), there is a broken link regarding to port-forwarding developer documentation (https://docs.openshift.com/container-platform/4.6/dev_guide/port_forwarding.html)

**Comment by cedricclyburn** [comment]
Thank you! Sorry for the late response, have fixed these links in latest 4.11 update.
