### ISSUE TITLE
Deleting the s2i build before introducing the pipeline ? 

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-scholars/openshift-starter-guides#4]
When I started my pipeline for the first time the redeploy phase failed because the was a conflict. I had to delete the build from the s2i build and after that I could run successfully the pipeline

**Comment by blues-man** [comment]
Was that conflict a redeploy already in progress? I'll test it again out thanks!

**Comment by sebastienblanc** [comment]
I ran the workshop this morning again and I could not reproduce this particular issue. So maybe it was something on my side.

**Comment by blues-man** [comment]
Did you run it on a different project or different cluster? This may happen due the triggers not disabled on the DeploymentConfig which would trigger a new deployment when the pipeline pushes the new container image.

**Comment by blues-man** [comment]
I did a test and I reproduced the issue once, it happens randomly apparantely, even if the triggers are disabled. I need to investigate more
