### ISSUE TITLE
S2I app fails to build

### ISSUE THREAD

**Issue by hunter86bg** [redhat-scholars/openshift-starter-guides#43]
It seems that something changed in the past 2 days, as the same app was building properly on 2nd of march.
[nationalparks-1-undefined.log.zip](https://github.com/redhat-scholars/openshift-starter-guides/files/8189409/nationalparks-1-undefined.log.zip)

**Comment by hunter86bg** [comment]
Seems that ubi8/openjdk-11 was updated to 1.11-2.1645811224 recently. As it's both usedin Openshift 4.9 and OKD 4.9 it might be the common link.

**Comment by jimbarlow** [comment]
I'm having the same issue, and I have a workshop scheduled for March 9th.

**Comment by blues-man** [comment]
Hi all, thanks for you comments, this has been solved with the above commit. Can you retry and confirm?

**Comment by hunter86bg** [comment]
The patch seems OK on OKD4.9:
```
$ oc get builds
NAME              TYPE     FROM          STATUS     STARTED         DURATION
nationalparks-6   Source   Git@307c859   Complete   2 minutes ago   2m16s
```

**Comment by hunter86bg** [comment]
@jimbarlow ,
can you confirm if it works for you ?

**Comment by jimbarlow** [comment]
@hunter86bg It worked for me. Thanks all for the quick resolution.

**Comment by hunter86bg** [comment]
Closing this one as it works both on Openshift 4.9 & OKD 4.9
