### ISSUE TITLE
Should Openshift Sandbox be the default tab instead of ROKS?

### ISSUE THREAD

**Issue by kdubois** [redhat-scholars/openshift-starter-guides#53]

**Comment by cedricclyburn** [comment]
Most definitely, just added it to #52 👍 

<img width="584" alt="Screen Shot 2023-03-31 at 2 12 41 PM" src="https://user-images.githubusercontent.com/54345140/229197909-829a74d8-84ca-4372-9a05-f0721f65d30f.png">
