### ISSUE TITLE
Github Workflow for Add Github Action build with deprecated ubuntu-18.04

### ISSUE THREAD

**Issue by szetattlee** [redhat-scholars/openshift-starter-guides#54]
The YAML file to be added to GitHub Action are still using deprecated runs-on: ubuntu-10.04 while current Github runner image uses Ubuntu-22.04.
Please correct this or reference it with ubuntu-latest. 

https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/4.11/nationalparks-codechanges-github-actions.html?#add_github_action

[Source](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)

**Comment by cedricclyburn** [comment]
Thanks for the heads up! Updated 👍
