### ISSUE TITLE
The sub sections of `Download CLI` are not highlighted

### ISSUE THREAD

**Issue by mcouliba** [redhat-scholars/openshift-starter-guides#6]
The following titles could be better highlighted (bold or underlined?)

`Download and Install OpenShift CLI on Linux`
`Download and Install OpenShift CLI on Mac OS X`
`Download and Install OpenShift CLI on Windows`

**Comment by blues-man** [comment]
Agree, they are 4-level sub-title so they came in that way, adding bold
